### ISSUE TITLE
Alpha version - Standardize usage of ellipses in command instruction

### ISSUE THREAD

**Issue by wujiaweijoanna** [AY2425S1-CS2103T-F08-2/tp#144]
For add, edit and delete command instruction, place the ellipsese inside the square brackets. 
Standardize to [t/STUDY_GROUP_TAG ...], as identical to the format in find command, instead of current [t/STUDY_GROUP_TAG]...
![屏幕截图(113)](https://github.com/user-attachments/assets/396dcf81-ab00-4939-8320-12addd55aaff)
![屏幕截图(114)](https://github.com/user-attachments/assets/66bd03d0-11d9-44c9-923f-8fcbdc630d67)

**Comment by k-hian** [comment]
I think this isn't a bug.
For `add` command, the format is `[t/STUDY_GROUP_TAG] ...` because to add multiple study groups, the user needs to type `t/Tag1 t/Tag2 t/Tag3`.
However, for `find` command, the format is `[t/STUDY_GROUP_TAG ...]` because to search multiple study groups, the user needs to type `t/Tag1 Tag2 Tag3`.

**Comment by wujiaweijoanna** [comment]
Oh I see, thx!
