### ISSUE TITLE
[PE-D][Tester F] Find command does not check for invalid tags

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F08-2/tp#296]
![Screenshot 2024-11-08 at 5.51.07 PM.png](https://raw.githubusercontent.com/yhanyi/ped/main/files/0a1c53b2-df12-451d-b4ca-4c0366db817b.png)

As per title

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: yhanyi/ped#17

**Comment by k-hian** [comment]
We understand what the tester is aiming to do with the command `find n/"John Doe"`, it is not part of our command specification.

Having such functionality will be beneficial, but the output is not "incorrect" (since there are no users whose name is `"John` or `Doe"`) and RR correctly returns an empty list.
